/**
 * Release gate 8.1: the real bin in a real PTY on a portable export, with no daemon and no
 * browser. The export is the real `kosmo-callflow export` of an errored Express checkout
 * (test/fixtures/cross-source, generated by kosmo-callflow's cross-source recording).
 *
 * Flow: open with `--replay` → seek to the recorded error and select the errored span →
 * `b` steps back one recorded state → the detail pane shows the span's recorded args →
 * `L` back to the snapshot → `f` records a finding with a note → `R` marks the review
 * ready → `q`. The review file must carry the snapshot evidence as a full versioned
 * trace-text document that parses back, with status `ready`; the terminal must be
 * restored after the normal exit and after error exits (a corrupted export, SIGTERM).
 *
 * Needs the built dist/ (`npm test` runs `pretest` → build) and script(1).
 */
import { execFileSync } from "node:child_process";
import { copyFileSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { parseReview, reparseEvidence } from "../src/review-format.js";
import {
  BIN,
  ENTER,
  RESTORE,
  count,
  distReady,
  expectCookedTty,
  scriptAvailable,
  shellQuote,
  startPty,
  sttyAfterClose,
  type PtySession
} from "./pty.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const EXPORT = path.join(here, "fixtures", "cross-source", "export-errored.json");

type ExportRecord = { seq: number; type: string; spanId: string; parentSpanId: string | null; nodeId: string };
const records = (JSON.parse(readFileSync(EXPORT, "utf8")) as { records: ExportRecord[] }).records;
const enterOf = (spanId: string) => records.find((record) => record.type === "enter" && record.spanId === spanId);
const errorRecord = records.find((record) => record.type === "error")!;
const errored = enterOf(errorRecord.spanId)!;

function project(): { dir: string; exportFile: string } {
  const dir = mkdtempSync(path.join(os.tmpdir(), "kosmo-tui-gate-8-1-"));
  mkdirSync(path.join(dir, ".kosmo-callflow"), { recursive: true });
  writeFileSync(path.join(dir, ".kosmo-callflow", "project.json"), JSON.stringify({ projectId: "cross-source" }));
  const exportFile = path.join(dir, "export.json");
  copyFileSync(EXPORT, exportFile);
  return { dir, exportFile };
}

/** Runs the bin in `dir`, then prints its exit code and the tty state it left behind. */
function command(dir: string, args: string): string {
  return (
    `cd ${shellQuote(dir)} && ${shellQuote(process.execPath)} ${shellQuote(BIN)} ${args}; ` +
    `echo EXIT=$?; echo STTY_AFTER_CLOSE=$(stty -a | tr '\\n' ' ')`
  );
}

const SIZE = { rows: 30, cols: 120 };

const escapeRegExp = (text: string) => text.replace(/[.*+?^${}()|[\]\\/]/g, "\\$&");

const settle = () => new Promise((resolve) => setTimeout(resolve, 120));

/**
 * One key per read: a coalesced chunk ("\rb") is not two keys to the decoder, so every
 * key is followed by a pause even when the expected screen is already there.
 */
async function press(s: PtySession, key: string, expected?: RegExp): Promise<string> {
  s.write(key);
  const screen = expected ? await s.waitForScreen(expected) : null;
  await settle();
  return screen ?? s.screen().join("\n");
}

/** Move the selection with j until the selected row names `nodeId`. */
async function select(s: PtySession, nodeId: string): Promise<void> {
  const selected = new RegExp(`^>.*${escapeRegExp(nodeId)}`, "m");
  for (let step = 0; step < 20; step += 1) {
    if (selected.test(s.screen().join("\n"))) return;
    await press(s, "j");
  }
  throw new Error(`could not select ${nodeId}; screen:\n${s.screen().join("\n")}`);
}

/** Select the root, expand it and walk down the recorded parent chain to `spanId`. */
async function selectSpan(s: PtySession, spanId: string): Promise<void> {
  const chain: ExportRecord[] = [];
  for (
    let current = enterOf(spanId);
    current;
    current = current.parentSpanId ? enterOf(current.parentSpanId) : undefined
  ) {
    chain.unshift(current);
  }
  await press(s, "g");
  for (const [index, span] of chain.entries()) {
    await select(s, span.nodeId);
    if (index < chain.length - 1) await press(s, "l");
  }
}
const gate = scriptAvailable && distReady ? describe : describe.skip;

gate("gate 8.1: export in a real PTY without daemon or browser", () => {
  it("error → b → args → f → R writes a ready review with parseable snapshot evidence; q restores the terminal", async () => {
    const { dir, exportFile } = project();
    const exported = readFileSync(exportFile);
    // No daemon: the only endpoint the environment could name is a closed port.
    const s = startPty(
      `KOSMO_CALLFLOW_ENDPOINT=http://127.0.0.1:9 ${command(dir, "./export.json --replay --step-interval 60s")}`,
      SIZE
    );
    try {
      await s.waitForScreen(/^export snapshot \| REPLAY 1\/\d+ seq=\d+/m);
      // Pause autoplay, then seek to the recorded error.
      await press(s, "p", /replay autoplay paused/);
      await press(s, ":", /^:_/m);
      await press(s, `seq ${errorRecord.seq}`, new RegExp(`^:seq ${errorRecord.seq}_`, "m"));
      await press(s, "\r", new RegExp(`REPLAY \\d+/\\d+ seq=${errorRecord.seq} `));
      // The errored span, found through its recorded parent chain; its detail says errored.
      await selectSpan(s, errored.spanId);
      await press(s, "\r", new RegExp(`detail: ${escapeRegExp(errored.nodeId)} \\[errored\\]`));
      // b: one recorded state back, before the error was recorded.
      const back = await press(s, "b", new RegExp(`REPLAY \\d+/\\d+ seq=(?!${errorRecord.seq} )\\d+ `));
      const backSeq = Number(/REPLAY \d+\/\d+ seq=(\d+) /.exec(back)![1]);
      expect(backSeq).toBeLessThan(errorRecord.seq);
      // The selected span at that earlier cutoff: running, its args recorded (the replay
      // path shows a value with any masked field as masked, never the raw secret).
      const detail = await s.waitForScreen(new RegExp(`detail: ${escapeRegExp(errored.nodeId)} \\[running\\]`));
      expect(detail).toMatch(/^ {2}args: \[masked\]$/m);
      expect(detail).not.toContain("hunter2-secret");
      // Back to the snapshot (findings are recorded against it, not a replay frame); the
      // snapshot's typed evidence shows the args with only the password masked.
      await press(s, "L", /^export snapshot \| capture: /m);
      await press(s, "\r");
      const snapshotDetail = await s.waitForScreen(
        /^ {2}args: \[\{"orderId":"o-2","card":"declined","password":"\[masked\]"/m
      );
      expect(snapshotDetail).toContain(`detail: ${errored.nodeId} [errored]`);
      expect(snapshotDetail).toMatch(/^ {2}error: .*card declined for order o-2/m);
      expect(snapshotDetail).not.toContain("hunter2-secret");
      await press(s, "f", /:finding _/);
      await press(s, "declined card is not retried", /:finding declined card is not retried_/);
      await press(s, "\r", /finding saved: /);
      await press(s, "R", /review ready: /);
      s.write("q");
      await s.waitFor(/EXIT=0/);
      await s.waitFor(/STTY_AFTER_CLOSE=/);
      s.child.stdin.end();
      await s.exited;

      const out = s.output();
      expect(count(out, ENTER)).toBe(1);
      expect(count(out, RESTORE)).toBe(1);
      expect(out.indexOf(RESTORE)).toBeLessThan(out.indexOf("EXIT=0"));
      expectCookedTty(sttyAfterClose(out));

      const reviews = path.join(dir, ".kosmo-callflow", "reviews");
      const files = readdirSync(reviews).filter((name) => name.endsWith(".md"));
      expect(files).toHaveLength(1);
      const parsed = parseReview(readFileSync(path.join(reviews, files[0]!), "utf8"));
      if (!parsed.ok) throw new Error(`review does not parse: ${parsed.message}`);
      expect(parsed.value.frontmatter.status).toBe("ready");
      expect(parsed.value.frontmatter.sourceRef).toMatchObject({ projectId: "cross-source" });
      const [finding] = parsed.value.findings;
      expect(parsed.value.findings).toHaveLength(1);
      expect(finding!.note).toBe("declined card is not retried");
      expect(finding!.ref).toMatchObject({ spanId: errored.spanId, projectId: "cross-source" });
      expect(finding!.node).toBe(errored.nodeId);
      // Snapshot evidence: a full, versioned trace-text document that parses back.
      expect(finding!.snapshot.snapshotId).toMatch(/\S/);
      expect(finding!.evidence.version).toBe(2);
      expect(finding!.evidence.text).toContain(":projection-version 2");
      expect(finding!.evidence.text).toContain(errored.nodeId);
      const reparsed = reparseEvidence(finding!.evidence);
      expect(reparsed.ok, JSON.stringify(reparsed)).toBe(true);
      // The export was only read.
      expect(readFileSync(exportFile).equals(exported)).toBe(true);
    } finally {
      s.kill();
      rmSync(dir, { recursive: true, force: true });
    }
  }, 60_000);

  it("a corrupted export fails with a source error (exit 2) and leaves the terminal untouched", async () => {
    const { dir, exportFile } = project();
    writeFileSync(exportFile, readFileSync(exportFile, "utf8").slice(0, 4000));
    const s = startPty(command(dir, "./export.json"), SIZE);
    try {
      await s.waitFor(/EXIT=2/);
      await s.waitFor(/STTY_AFTER_CLOSE=/);
      s.child.stdin.end();
      await s.exited;
      const out = s.output();
      expect(out).toMatch(/kosmo-tui: .*export/i);
      // Raw mode/alt screen are never entered, or they are restored exactly as often.
      expect(count(out, RESTORE)).toBe(count(out, ENTER));
      expectCookedTty(sttyAfterClose(out));
      expect(readdirSync(path.join(dir, ".kosmo-callflow"))).not.toContain("reviews");
    } finally {
      s.kill();
      rmSync(dir, { recursive: true, force: true });
    }
  }, 30_000);

  it("SIGTERM mid-review restores the terminal once, exits 143 and leaves a parseable review", async () => {
    const { dir } = project();
    const s = startPty(command(dir, "./export.json"), SIZE);
    try {
      await s.waitForScreen(/^export snapshot \| capture: /m);
      await selectSpan(s, errored.spanId);
      await press(s, "f", /:finding _/);
      await press(s, "before the signal", /:finding before the signal_/);
      await press(s, "\r", /finding saved: /);
      // The viewer is the node child of the shell inside the PTY.
      // The viewer is the node process itself (argv[0] = node), not the shells around it.
      const pids = execFileSync("pgrep", ["-f", `^${process.execPath} ${BIN} ./export.json`], { encoding: "utf8" })
        .trim()
        .split("\n");
      expect(pids).toHaveLength(1);
      const pid = Number(pids[0]);
      process.kill(pid, "SIGTERM");
      await s.waitFor(/EXIT=143/);
      await s.waitFor(/STTY_AFTER_CLOSE=/);
      s.child.stdin.end();
      await s.exited;
      const out = s.output();
      expect(count(out, ENTER)).toBe(1);
      expect(count(out, RESTORE)).toBe(1);
      expect(out.indexOf(RESTORE)).toBeLessThan(out.indexOf("EXIT=143"));
      expectCookedTty(sttyAfterClose(out));
      const reviews = path.join(dir, ".kosmo-callflow", "reviews");
      const files = readdirSync(reviews).filter((name) => name.endsWith(".md"));
      expect(files).toHaveLength(1);
      const parsed = parseReview(readFileSync(path.join(reviews, files[0]!), "utf8"));
      expect(parsed.ok).toBe(true);
      if (parsed.ok) {
        expect(parsed.value.frontmatter.status).toBe("editing");
        expect(parsed.value.findings.map((finding) => finding.note)).toEqual(["before the signal"]);
      }
    } finally {
      s.kill();
      rmSync(dir, { recursive: true, force: true });
    }
  }, 30_000);
});
